# -*- coding: utf-8 -*-
"""drowsiness_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRHQO6KpvCgB1rlsPdmB9xvWHuIayQWW
"""

import numpy as np
import pandas as pd
import os
import cv2
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

folder_dir = 'drive/MyDrive/train/'
labels = os.listdir(folder_dir)
labels

plt.imshow(plt.imread(folder_dir+"Closed/_26.jpg"))

plt.imshow(plt.imread(folder_dir+"yawn/109.jpg"))  # display the first image in the yawn_no_yawn list

"""## Preprocessing Images
### Yawning Dataset: Resizing + Crop Faces + Yawning Label
"""

def face_for_yawn(direc=folder_dir, face_cas_path=cv2.data.haarcascades + "haarcascade_frontalface_default.xml"):
    yaw_no = []  # create an empty list to store .image arrays and their respective class numbers
    IMG_SIZE = 145  # define the size of the image to be resized to
    categories = ["yawn", "no_yawn"]  # define the categories of the images
    for category in categories:
        path_link = os.path.join(direc, category)  # create a path to the directory of each category
        class_num1 = categories.index(category)  # assign a unique class number to each category
        print(class_num1)  # print the class number for debugging purposes
        for image in os.listdir(path_link):  # loop through all the images in the directory
            image_array = cv2.imread(os.path.join(path_link, image), cv2.IMREAD_COLOR)  # read the image and store it as an array
            face_cascade = cv2.CascadeClassifier(face_cas_path)  # load the face cascade classifier
            faces = face_cascade.detectMultiScale(image_array, 1.3, 5)  # detect all faces in the image
            for (x, y, w, h) in faces:  # loop through all the detected faces
                img = cv2.rectangle(image_array, (x, y), (x+w, y+h), (0, 255, 0), 2)  # draw a rectangle around the face
                roi_color = img[y:y+h, x:x+w]  # crop the image to only include the face
                resized_array = cv2.resize(roi_color, (IMG_SIZE, IMG_SIZE))  # resize the cropped image to the desired size
                yaw_no.append([resized_array, class_num1])  # add the resized image and its class number to the list
    return yaw_no  # return the list of resized images and their class numbers


yawn_no_yawn = face_for_yawn()  # call the face_for_yawn function and store the result in yawn_no_yawn variable

"""### Eyes Dataset: Resizing Images + Eyes Label"""

# This function is getting data from a directory
# It is resizing the images to a specified size and appending the resized image and its label to a list
# The function returns the list of data
def get_data(dir_path=folder_dir):
    # Define the labels for the data
    labels = ['Closed', 'Open']
    # Define the size of the images after resizing
    IMG_SIZE = 145
    # Create an empty list to store the data
    data = []
    # Loop through each label in the labels list
    for label in labels:
        # Define the path to the label's directory
        path = os.path.join(dir_path, label)
        # Get the index of the label in the labels list
        class_num = labels.index(label)
        # Add 2 to the class number to account for the additional classes for face and eyes
        class_num += 2
        # Loop through each image in the label's directory
        for img in os.listdir(path):
            try:
                # Read in the image and resize it
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_COLOR)
                resized_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                # Append the resized image and its label to the data list
                data.append([resized_array, class_num])
            except Exception as e:
                print(e)
    # Return the list of data
    return data
data_train = get_data()

data_train[0][0].shape

"""### Preprocessed Data Combination"""

def append_data():
    # call the `face_for_yawn()` function to get yawning and non-yawning face images
    yaw_no = face_for_yawn()

    # call the `get_data()` function to get open and closed eye images
    data = get_data()

    # combine the two datasets into a single list using the `extend()` method
    yaw_no.extend(data)

    # return the resulting list as a standard Python list
    return yaw_no

new_data = append_data()

"""### Transforming Appended Dataset and Splitting Features"""

# Initialize empty lists to store features and labels
X = []
y = []

# Iterate over each tuple of feature and label in the new_data list
for feature, label in new_data:

    # Append the feature to the X list
    X.append(feature)

    # Append the label to the y list
    y.append(label)
# Features
X = np.array(X)
X = X.reshape(-1, 145, 145, 3)

"""### One-hot Encoding the Labels (possible classes 0,1,2,3) using Label Binarizer"""

from sklearn.preprocessing import LabelBinarizer
label_bin = LabelBinarizer()
y = label_bin.fit_transform(y)

# Labels
y = np.array(y)

"""### Data Splitting"""

from sklearn.model_selection import train_test_split
seed = 42
test_size = 0.20
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=seed, test_size=test_size)

"""### Importing Modules"""

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf

"""### Data Augmentation"""

train_generator = ImageDataGenerator(rescale=1/255, zoom_range=0.2, horizontal_flip=True, rotation_range=30)
test_generator = ImageDataGenerator(rescale=1/255)

train_generator = train_generator.flow(np.array(X_train), y_train, shuffle=False)
test_generator = test_generator.flow(np.array(X_test), y_test, shuffle=False)

"""### Model Compiling"""

# Create a Sequential model
model = Sequential()

# Add convolutional layers with ReLU activation and MaxPooling layers
model.add(Conv2D(512, (3, 3), activation="relu", input_shape=X_train.shape[1:]))
model.add(MaxPooling2D(2, 2))
model.add(Conv2D(512, (3, 3), activation="relu"))
model.add(MaxPooling2D(2, 2))
model.add(Conv2D(256, (3, 3), activation="relu"))
model.add(MaxPooling2D(2, 2))
model.add(Conv2D(256, (3, 3), activation="relu"))
model.add(MaxPooling2D(2, 2))
model.add(Conv2D(256, (3, 3), activation="relu"))
model.add(MaxPooling2D(2, 2))

# Flatten the output and add a Dropout layer
model.add(Flatten())
model.add(Dropout(0.5))

# Add Dense layers with ReLU activation and a Softmax output layer
model.add(Dense(128, activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(4, activation="softmax"))

# Compile the model with categorical cross-entropy loss, accuracy metric, and Adam optimizer
model.compile(loss="categorical_crossentropy", metrics=["accuracy"], optimizer="adam")

# Print the model summary
model.summary()

from tensorflow.keras.callbacks import EarlyStopping

# Define the EarlyStopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',  # Monitor validation loss
    patience=20,         # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True # Restore model weights from the epoch with the best value of the monitored quantity.
)

history = model.fit(train_generator, epochs=50, validation_data=test_generator, shuffle=True, validation_steps=len(test_generator), callbacks=[early_stopping])

"""## Saving the Model"""

model.save("drowiness_from_scratch.keras")

test_loss, test_acc = model.evaluate(test_generator)

def get_label(prediction_label):
    if prediction_label == 0:
        print("STAY ALERT! YOU'RE DOZING OFF!")
        print("Yawning Detected")
    elif prediction_label == 1:
        print("No Yawning Detected")
    elif prediction_label == 2:
        print("STAY ALERT! YOU'RE DOZING OFF!")
        print("Eyes are closed")
    elif prediction_label == 3:
        print("Eyes are open")
    else:
        raise ValueError("Invalid index")